import { BookItem } from '@/types/database';

// 38-Book Authentic FOLK Reading Catalogue across 5 Progressive Levels with High-Res Covers
export const folkBookCatalogue: BookItem[] = [
  // LEVEL 1: Foundational Literature
  {
    id: 'b-01',
    order: 1,
    level: 1,
    title: 'Beyond Birth & Death',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Beyond Birth and Death.jpeg',
  },
  {
    id: 'b-02',
    order: 2,
    level: 1,
    title: 'PQQA (Perfect Questions, Perfect Answers)',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Perfect_Questions_Perfect_Answers_wOMObWv_04pKdaN.jpg',
  },
  {
    id: 'b-03',
    order: 3,
    level: 1,
    title: 'On the Way to Krishna',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/On_the_Way_to_Krsna-1973_book.jpg',
  },
  {
    id: 'b-04',
    order: 4,
    level: 1,
    title: 'Krishna: The Reservoir of Pleasure',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/KRSNA_the_Reservoir_of_Pleasure.jpg',
  },
  {
    id: 'b-05',
    order: 5,
    level: 1,
    title: 'Second Chance',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/second chance.jpg',
  },
  {
    id: 'b-06',
    order: 6,
    level: 1,
    title: 'Raja-Vidya: The King of Knowledge',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Raja-Vidhya_HAY9BY4_7AP76uZ.jpg',
  },
  {
    id: 'b-07',
    order: 7,
    level: 1,
    title: 'The Laws of Nature',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/The-Laws-of-Nature-An-Infallible-Justice.jpg',
  },

  // LEVEL 2: Intermediate Devotional Science
  {
    id: 'b-08',
    order: 8,
    level: 2,
    title: 'Elevation to Krishna Consciousness',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Elevation-to-Krsna-Consciousness-Original-1973-edition.jpg',
  },
  {
    id: 'b-09',
    order: 9,
    level: 2,
    title: 'KC - The Matchless Gift',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Matchless Gift.webp',
  },
  {
    id: 'b-10',
    order: 10,
    level: 2,
    title: 'The Perfection of Yoga',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/The_Perfection_of_Yoga.jpg',
  },
  {
    id: 'b-11',
    order: 11,
    level: 2,
    title: 'Topmost Yoga System',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/KRSNA-Consciousness-The-Topmost-Yoga-System.jpg',
  },
  {
    id: 'b-12',
    order: 12,
    level: 2,
    title: 'Path of Perfection',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Path-of-Perfection.webp',
  },
  {
    id: 'b-13',
    order: 13,
    level: 2,
    title: 'Introduction to Bhagavad Gita',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Introduction-to-Bhagavad-gita.webp',
  },

  // LEVEL 3: Advanced Philosophical Inquiry
  {
    id: 'b-14',
    order: 14,
    level: 3,
    title: 'Easy Journey to Other Planets',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Easy-Journy-to-Other-Planets_-_His_Divine_Grace_A.C.Bhaktivedanta_Swami_Prabhupada.jpg',
  },
  {
    id: 'b-15',
    order: 15,
    level: 3,
    title: 'Life Comes from Life',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Life-Comes-from-Life.jpg',
  },
  {
    id: 'b-16',
    order: 16,
    level: 3,
    title: 'Dharma: The Way of Transcendence',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/dharma.webp',
  },
  {
    id: 'b-17',
    order: 17,
    level: 3,
    title: 'Science of Self Realization (SSR)',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/TheScienceofSelfRealization_1.webp',
  },
  {
    id: 'b-18',
    order: 18,
    level: 3,
    title: 'The Hare Krishna Challenge',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Hare-Krishna-Challenge.webp',
  },
  {
    id: 'b-19',
    order: 19,
    level: 3,
    title: 'Coming Back: The Science of Reincarnation',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/coming-back-the-science-of-reincarnation.webp',
  },
  {
    id: 'b-20',
    order: 20,
    level: 3,
    title: 'Message of Godhead',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/v_Message_Of_Godhead-600x895.webp',
  },
  {
    id: 'b-21',
    order: 21,
    level: 3,
    title: 'Civilization and Transcendence',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/civilization-and-transcendence.webp',
  },

  // LEVEL 4: Deep Shastric Study
  {
    id: 'b-22',
    order: 22,
    level: 4,
    title: 'Transcendental Teachings of Prahlada Maharaja',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Teachings of Prahlada Maharaj.webp',
  },
  {
    id: 'b-23',
    order: 23,
    level: 4,
    title: 'Teachings of Lord Chaitanya (TLC)',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Teachings-of-Lord-Chatanya_mT5GSXe.png',
  },
  {
    id: 'b-24',
    order: 24,
    level: 4,
    title: 'Journey of Self Discovery',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/the journey of self Discovery.webp',
  },
  {
    id: 'b-25',
    order: 25,
    level: 4,
    title: 'Bhagavad Gita As It Is',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Bhagavad Gita - As it is.jpeg',
  },
  {
    id: 'b-26',
    order: 26,
    level: 4,
    title: 'Krishna Book (Vols 1 & 2)',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/krsna_book.jpg',
  },
  {
    id: 'b-27',
    order: 27,
    level: 4,
    title: 'The Nectar of Instruction (Upadesamrita)',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Nectar of Instruction.jpg',
  },
  {
    id: 'b-28',
    order: 28,
    level: 4,
    title: 'Sri Isopanishad',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Sri Isoupnisad.jpg',
  },

  // LEVEL 5: Śrīmad-Bhāgavatam (10 Cantos)
  {
    id: 'sb-01',
    order: 29,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 1: Creation',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-02',
    order: 30,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 2: The Cosmic Manifestation',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-03',
    order: 31,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 3: The Status Quo',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-04',
    order: 32,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 4: Creation of Fourth Order',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-05',
    order: 33,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 5: The Creative Impetus',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-06',
    order: 34,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 6: Prescribed Duties for Mankind',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-07',
    order: 35,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 7: The Science of God',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-08',
    order: 36,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 8: Withdrawal of Cosmic Creations',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-09',
    order: 37,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 9: Liberation',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
  {
    id: 'sb-10',
    order: 38,
    level: 5,
    title: 'Śrīmad-Bhāgavatam Canto 10: The Summum Bonum',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    cover_url: '/assets/images/books/Srimad_Bhagavatam.jpg',
  },
];

export function getBookCoverUrl(title?: string): string {
  if (!title) return '/assets/images/books/Bhagavad Gita - As it is.jpeg';
  const found = folkBookCatalogue.find(
    (b) => b.title.toLowerCase().trim() === title.toLowerCase().trim()
  );
  return found?.cover_url || '/assets/images/books/Bhagavad Gita - As it is.jpeg';
}
